name: CI/CD Pipeline

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

        
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e


            echo "===> Checking repo..."
            if [ ! -d ~/ci_cd_session/.git ]; then
              echo "===> Repo not found. Cloning..."
              git clone https://github.com/zain-dev25/education_material_Backend.git ~/education_material_Backend

              cd ~/ci_cd_session
            else
              echo "===> Repo exists. Pulling latest..."
              cd ~/ci_cd_session
            fi
            git pull origin main
            echo "===> Repo is ready."
            echo "===> Installing dependencies..."
            npm install
            npm run dev
